packages/design-system/package.json
packages/design-system/src/icons/src/SymbolLogo.tsx

> - #41 
import문 자동생성되지 않도록 svgr 옵션 추가
- svgr로 svg 파일 변환할때 생기는 필요없는 import문이 생기지 않도록 옵션을 추가합니다.
- design-system의 package.json 파일에서 svgr 관련 스크립트에 --jsx-runtime automatic 옵션을 추가하여, jsxRuntime 설정을 자동으로 적용
pnpm svgr 실행 후 변환된 tsx 파일에 `import * as React from 'react';` 안뜸!!

Refactor: 불필요한 import문 자동생성되지 않도록 svgr 옵션 추가

---

apps/client/src/pages/my/page/confeti-detail.css.ts
apps/client/src/pages/my/page/confeti-detail.tsx
apps/client/src/shared/constants/path.ts
apps/client/src/shared/mocks/performance-data.ts
apps/client/src/shared/router/lazy.ts
apps/client/src/shared/router/router.tsx
packages/design-system/src/components/festival-card/festival-card.css.ts

> - #77 )
공연 더보기 페이지를 퍼블리싱 했어요.
- my confeti 페이지 라우팅 추가
- 페이지 퍼블리싱
- festival card 사이즈 조정
반응형 고려하여 festival card의 height 수정하였습니다.
명세서 참고하여 PERFORMANCE_DATA 임시로 설정했습니다.

Feat(client): 공연 더보기 페이지 퍼블리싱

---

apps/client/src/pages/my/components/artist-section.css.ts
apps/client/src/pages/my/components/artist-section.tsx
apps/client/src/pages/my/components/box.css.ts
apps/client/src/pages/my/components/box.tsx
apps/client/src/pages/my/components/confeti-section.css.ts
apps/client/src/pages/my/components/conteti-section.tsx
apps/client/src/pages/my/components/no-artist-section.css.ts
apps/client/src/pages/my/components/no-artist-section.tsx
apps/client/src/pages/my/components/no-confeti-section.css.ts
apps/client/src/pages/my/components/no-confeti-section.tsx
apps/client/src/pages/my/components/user-info.css.ts
apps/client/src/pages/my/page/my.tsx
apps/client/src/shared/mocks/artists-data.ts
packages/design-system/package.json
packages/design-system/src/components/artist-card/artist-card.css.ts
packages/design-system/src/components/artist-card/artist-card.stories.tsx
packages/design-system/src/components/artist-card/artist-card.tsx
packages/design-system/src/components/footer/footer.css.ts
packages/design-system/src/components/index.ts
packages/design-system/src/styles/global.css.ts
packages/design-system/src/styles/reset.css.ts

> - #75 
마이페이지 뷰를 퍼블리싱 했어요.
- 마이페이지 뷰 제작
- ArtistCard CSS 반응형 수정
- reset.css내 글자 간격 초기화 코드 추가
- ds package.json내 아이콘 export 추가
- Footer 하단 고정 기능 추가

Feat(client): 마이페이지 퍼블리싱

---

apps/client/src/shared/mocks/performance-data.ts
packages/design-system/src/components/festival-card/festival-card.css.ts

> - #119 
페스티벌 카드 모바일 화면 깨짐 이슈를 해결했어요
- festival-card 컴포넌트 title에 width값 지정
반응형 대응을 위해 title에 width에 고정값을 넣지 않고, `wordBreak: keep-all`을 지정해주었는데 해당 부분 때문에 이슈가 발생했습니다. width에 10rem을 지정해주어서 해결했습니다!
이슈를 해결함으로써 스크린크기에 따라 이미지 크기는 늘어나지만, title은 width값이 고정되어있어서 적용되지 않습니다. 
하지만 title의 정확한 정보(부자연스러운 띄어쓰기)를 제공하기 위해서는 어쩔 수 없는 것 같아요. UX와 연결되는 부분이기도 하고요 !

Fix(design-system): 페스티벌 카드 모바일 화면 깨짐 해결

---

packages/design-system/src/components/navigation/navigation.tsx

> - #114 
- 스타일 깨지게 적용되는 부분 수정
첫번째 렌더링시에는 잘 보여지나, 여러번 클릭시 스타일이 깨지는 걸로 보아 캐시된 스타일이 예정대로 적용되지 않는 문제라고 추측되어 NavItem 버튼에 key를 추가하여 상태 변경시 리렌더링하도록 해줬다.
```
<button
key={activeTab} 
>
```

Fix: (QA/1) 스타일 깨지게 적용되는 부분 수정

---

apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts
apps/client/src/pages/time-table/components/empty/empty-festival-section.tsx
apps/client/src/pages/time-table/page/empty/empty-festival.tsx
apps/client/src/pages/time-table/page/time-table-layout.tsx
apps/client/src/shared/constants/path.ts
apps/client/src/shared/router/lazy.ts
apps/client/src/shared/router/router.tsx

- #102 
- 페스티벌 추가 안내 페이지를 구현하였습니다.
`line height` 적용 아직도 안 되네요... 임의로 설정해둘까요? @m2na7 
추가된 페스티벌이 없을 때 나오는 안내 페이지인데 우선 컴포넌트 폴더 이름을` empty`로 해놓았습니다. 혹시 더 좋은 네이밍이 있다면 추천해주세요... 🥲 컴포넌트 이름은 `empty-festival-section` 인데 `empty-festival `보다 더 좋은 게 있다면 또 추천 부탁드립니다,, ㅠㅠ
경품: 추파춥스 1개 ^^ !!!;;
https://github.com/user-attachments/assets/5990cf54-b368-4fe1-aa19-d2c898f95157

Feat(client): 페스티벌 추가 안내 페이지 구현

---

apps/client/src/pages/confeti/components/summary.tsx
apps/client/src/pages/search/components/performance-info.css.ts
apps/client/src/pages/search/components/performance-info.tsx
apps/client/src/pages/search/components/performance-section.tsx
apps/client/src/pages/search/components/title.tsx

> - #112 
검색 페이지 내에서 검색결과 - 예정된 공연 카드 클릭시 id 값에 맞는 게시물(콘서트or페스티벌)로 이동하는 기능을 구현했습니다.
- 검색 페이지 내 공연 상세보기 기능 구현
https://github.com/user-attachments/assets/e16c2cdf-4f0f-401a-8ef2-2c56cbabdb86

Feat(client): 검색 페이지 목록에서 공연 상세 페이지로 라우팅

---

apps/client/src/pages/time-table/hooks/use-festival-selection.ts
apps/client/src/pages/time-table/page/add-festival.tsx
packages/design-system/src/components/festival-card/festival-card.tsx

> - #142 
페스티벌 추가하기 페이지 내의 toast 띄우는 로직을 수정합니다.
- 추가하기 버튼 클릭시 toast 띄우기
- 기존에는 페스티벌 카드를 4개부터는 선택조차 못하도록 막고 토스트를 띄웠었는데
- 선택은 가능하되, 4개 이상 선택 후 추가하기 버튼을 누르면 토스트를 띄우는 것으로 수정하였습니다.

Fix(client): 페스티벌 추가 페이지 기능 수정

---

apps/client/src/pages/time-table/page/add-festival.css.ts
apps/client/src/pages/time-table/page/add-festival.tsx
packages/design-system/src/components/header/header.tsx

> - #160 
- 디자인 시스템 헤더에 cn을 추가해서 className prop으로 컴포넌트의 스타일을 추가할 수 있도록 변경했습니다.
- 헤더와 하단 고정되도록 수정
https://github.com/user-attachments/assets/07d613fa-431f-4a11-b8c4-74253470c883

Fix(client, design-system): 페스티벌 추가페이지 스타일 에러 해결

---

apps/client/src/pages/time-table/components/calender/calender.css.ts
apps/client/src/pages/time-table/components/calender/calender.tsx
apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
apps/client/src/pages/time-table/hooks/use-button-selection.ts
apps/client/src/pages/time-table/hooks/use-disabled-scroll.ts
apps/client/src/pages/time-table/hooks/use-edit-mode.ts
apps/client/src/pages/time-table/hooks/use-scroll-position.ts
apps/client/src/pages/time-table/page/time-table.tsx
apps/client/src/pages/time-table/types/time-table-info-type.ts

> - #162 
타임테이블 EditFloatingButton관련 훅들과 레이아웃 관련 이슈를 수정했어요.
- use-scroll-position훅 추가
- use-edit-mode훅 추가
- 플로팅 버튼이 편집하기 버튼을 가리는 이슈 수정
스크롤 위치에따라서 플로팅버튼이 위로 올라가도록(편집하기 버튼을 가리지 않도록)수정했어요.
isEditTimeTableMode, isFestivalDeleteMode 일때는 '이미지 저장하기'버튼을 가리지 않도록 기능을 추가했어요.
자세한 포지션값은 추후에 디자이너분과 이야기 후 수정할 예정이에요.
TimeTable페이지 내에서 편집하기 상태를 EditFloatingButton으로 넘겨주도록 로직을 수정했어요.
추후에 편집하기 API를 연동할때 해당 훅에서 상태를 가져오기만 한다면 쉽게 연동이 가능하도록 했습니다.
추가로 현재 개발자도구없이 웹에서 보면 플로팅버튼이 우측하단에 위치하고있어요. 
https://github.com/user-attachments/assets/7d6a40b7-a009-40e5-b890-5a99be0b2272

Feat(client): 타임테이블 EditFloatingButton 기능 구현

---

apps/client/index.html
apps/client/src/pages/search/hooks/use-search-logic.ts
apps/client/src/pages/search/page/search.tsx
packages/design-system/src/components/search-bar/search-bar.tsx

- #122 
- iOS에서 Input창 눌러도 확대 안 되게 수정했습니다.
- 기존에는 엔터를 눌러도 커서가 안 꺼졌기 때문에 모바일에서 보면 검색을 해도 키보드가 내려가지 않는 이슈가 있었습니다. 이를 엔터를 치면 커서가 꺼지게끔 수정하였습니다.
- 검색할 때 사용자 경험을 위해 사용자의 키보드 `엔터` 부분이 `검색`으로 뜨게끔 기능을 추가하였습니다.
Enter 키를 누를 때 searchKeyword가 상태로 업데이트되면서 입력 필드가 리렌더링되고 키 입력 이벤트가 두 번 처리되는 현상이 발생했습니다. 이로 인해 '데이식스'를 검색하면 '데이식스스'처럼 키 입력이 중복되는 문제가 생겼습니다 🥲
이를 `setTimeout`을 사용하여 상태 변경과 네비게이션을 이벤트 루프의 다음 단계로 분리했습니다. 또한 e.preventDefault()로 브라우저의 기본 Enter 동작을 방지하여 이벤트가 중복 실행되지 않도록 했는데요,,, 만약 다른 방식으로도 문제를 해결할 수 있는 아이디어가 있다면 피드백 부탁드립니다!

Fix(client): iOS에서 input창 확대 되는 이슈 해결

---

apps/client/src/pages/confeti/components/summary/summary.tsx
apps/client/src/pages/confeti/page/concert-detail.tsx
apps/client/src/pages/confeti/page/festival-detail.tsx
apps/client/src/shared/apis/like/like.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/hooks/use-like-mutation.ts

> - #147 
콘서트 좋아요 추가/삭제 API를 연동합니다.
- 콘서트 좋아요 추가/삭제 API 연동
- 아직 api 에러(?) 수정 안 돼서 연결되는지 확인은 못했지만 일단 푸시했습니다..~
- 확인했습니다~~~
<!--
--!>

Feat(client): 콘서트 좋아요 추가, 삭제 api 연결

---

packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts

* #117 
* 자간의 악마 `신수진`이 명령한 자간간격 조정했습니다.
to 디자이너에게

Fix(design-system): progress-bar 및 ticketing-carousel 글자 간격 조정

---

packages/design-system/src/components/ticketing-carousel/hooks/use-data-format.ts

> - #243 
메인 페이지 하단 배너의 디데이 계산 오류를 수정했니다.
- 메인 페이지 하단 배너 디데이 계산 오류 수정
currentDate와 targetDate 간의 시간 차이를 계산할 때 시간 단위는 버리고 날짜만 비교하도록 currentDate와 targetDate의 시간을 초기화했습니다~

Fix(design-system): 디데이 계산 로직 수정

---

apps/client/src/pages/home/page/home.tsx
apps/client/src/pages/my/hooks/use-my-favorites.ts
apps/client/src/pages/my/hooks/use-user-info.ts
apps/client/src/pages/my/page/artist/artist-more.tsx
apps/client/src/pages/my/page/confeti/confeti-more.tsx
apps/client/src/pages/my/page/profile/my-profile.tsx

- #210 
- 비회원일 때 api 요청 막아두는 기능 구현
`suspensequery`에선 `enabled`를 사용하지 못해서 `useQuery`로 변경했습니다
https://github.com/user-attachments/assets/5e219ace-cb58-40bd-9f61-f28b70567ac7

Fix(client): (QA/4) 비로그인 상태로 홈화면 이동시 에러 수정

---

apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
apps/client/src/pages/time-table/hooks/use-button-selection.ts
apps/client/src/pages/time-table/page/time-table.tsx
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.tsx

* #274 
* 타임 테이블 이미지 저장시에 파일명이 선택된 공연명으로 저장되도록 수정하였습니다.
변경사항 잡힌 컴포넌트들 리팩토링 필수입니다...
며칠 전 수정한 자간 간격 수정한 코드가 병합하면서 날라갔나봐요... 변경 파일 꼼꼼히 서로서로 확인하기~👌

Fix(client): 타임테이블 이미지 저장 개선

---

apps/client/src/pages/confeti/components/expanded/expanded-section.css.ts
apps/client/src/pages/confeti/components/expanded/expanded-section.tsx
apps/client/src/pages/confeti/components/performance/performance-detail.css.ts
apps/client/src/pages/time-table/components/info/info-button.css.ts
apps/client/src/pages/time-table/components/info/info-button.tsx
apps/client/src/pages/time-table/page/time-table.tsx

> - #278 
- 페스티벌 삭제모드시 애니메이션 추가
- 상세정보 펼치기 애니메이션 추가
- 아티스트 목록 펼치기 애니메이션 추가
https://github.com/user-attachments/assets/7b084c31-5098-4ea3-9a8c-a89309b0216b
https://github.com/user-attachments/assets/b744c4d3-01f6-4c43-9436-df2924cdddab

Feat(client): 애니메이션 추가를 통한 UX개선

---

apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/page/search.tsx
apps/client/src/pages/time-table/page/add-festival.tsx
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/apis/search/search.ts
apps/client/src/shared/types/search-reponse.ts

- #275 
- 공연 정보 조회 무한 스크롤 구현 및 공연 개수도 서버 응답값 사용하게 수정하였습니다.

Fix(client): 공연 정보 조회 무한 스크롤 해결 및 공연 개수 api 연결

---

apps/client/src/pages/confeti/components/expanded/expanded-section.css.ts
apps/client/src/pages/time-table/components/add/add-button.tsx
apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
apps/client/src/pages/time-table/components/info/info-button.tsx
apps/client/src/pages/time-table/hooks/use-button-selection.ts
apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
apps/client/src/pages/time-table/page/time-table.tsx
apps/client/src/shared/types/festival-timetable-response.ts

> - #253 
- 선택된 페스티벌 삭제 시 자동으로 남아있는 페스티벌 중 첫번째를 선택되게 수정
- 삭제모드일때 추가하기 버튼 disabled 되도록 추가
https://github.com/user-attachments/assets/a0362d78-b5cd-49c3-b7e6-9b582d981a00

Fix: (QA/4) 페스티벌 삭제 시 이슈 해결

---

apps/client/src/pages/confeti/components/artist/artist-section.tsx
apps/client/src/pages/confeti/components/performance/performance-detail.css.ts
apps/client/src/pages/confeti/page/concert-detail.tsx
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts

* #293 
* 콘서트 페이지에서 상태하나 추가해서 prop depth 1로 뚫어놨습니다. 
* 하단 배너 줄 바꿈 UI도 수정하였어요 
* 일단 급하게 짠 로직이라 어설픈게 많아요 추후 리팩토링 필요합니다.
콘서트 페이지에서 아티스트가 4명 이상일 때에만 더보기 버튼이 보이도록 수정하였습니다.

Fix(client): 콘서트 더보기 버튼 기능 수정

---

packages/design-system/src/components/artist-card/artist-card.css.ts
packages/design-system/src/components/artist-card/artist-card.stories.tsx
packages/design-system/src/components/festival-card/festival-card.stories.tsx
packages/design-system/src/components/floating-button/floating-button.css.ts
packages/design-system/src/components/floating-button/floating-button.stories.tsx
packages/design-system/src/components/like-button/like-button.stories.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.stories.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

* #304 
디자인 시스템 내에서  `Card` 의 mock 데이터를 실제 이미지 파일로 변경합니다
Card 컴포넌트의 샘플 데이터를 실제 이미지 url 로 변경해두었습니다. UI를 스토리북 내에서 판단하기에 해당 방법이 더 적합하다고 생각했어요.
일단 이러한 방법이 옳은지에 대해서도 잘 모르겠어요.. 레퍼런스가 많이 없어서 추가적으로 고민되는 부분은  
위 사진과 같이 현재 `Festival Card` 도 마찬가지로 dummy data 로 설정되어있어요. 스토리북에서 mock 데이터를 활용하는 이유는 서버와의 의존성을 낮추기 위함인데 `Card` 컴포넌트의 경우 현재 사용하는 `Spotify` API 에서 가져오는 url 이라 무관할 것 같지만,
Festival Card에 사용되는 이미지 url 의 경우 서버 자체 S3 버킷에서 제공하는 파일 url 이라 dummy data를 수정해야 할지 고민이에요... 
제가 생각해본 방법은 아래와 같아요
1. mock data 자체를 정적 파일로 저장해둔다. ex ) public/assets 등등..
2. 현상 유지한다.
2번의 경우 
```
Card 컴포넌트의 샘플 데이터를 실제 이미지 url 로 변경해두었습니다. UI를 스토리북 내에서 판단하기에 해당 방법이 더 적합하다고 생각했어요.
```
이 의견에도 동의하지 않는다고 생각할 수 있어요 의견 부탁드립니다~
💦반대가 많을 시 브랜치 삭제하고 튑니다. 브삭튀 🛵💦💦💦💦
---
* 좋아요 버튼 스토리북내에서 사이즈가 너무 작은 것 같아 실제 confeti.co.kr 에 사용되는 사이즈와 거의 유사하게 조정하였습니다

Docs(design-system): CSS 스타일 수정 및 스토리북 데이터 업데이트

---

apps/client/src/pages/time-table/constants/index.ts
apps/client/src/pages/time-table/hooks/use-festival-selection.ts
apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
apps/client/src/pages/time-table/page/add-festival.tsx

* #306 
* handleAddClick 함수 분리 및 로직 개선
기존 문제점에 대한 사항은 연결 된 이슈에 작성해두었습니다 ! 확인해주세요 !
❗ 변경사항에 관련 된 설명을 리뷰로 달아두었습니다 확인부탁드려요!
https://github.com/user-attachments/assets/0f5c2552-f0fc-4def-9ef9-b6555e0e25a5
https://github.com/user-attachments/assets/046100f0-86ed-4bb4-8e5a-b1c4e0a65b05
---
개선 내용 주요 내용
* 코드 레벨에서의 개선 사항들은 모두 리뷰로 남겨두었습니다 
* 같은 url 의 api 요청 중복 요청(필요없는 요청) 을 제거하였습니다.
* 이미 등록된 페스티벌이 없는 케이스에서 -> 유저가 페스티벌을 추가하면 UI 에 해당 사항이 반영되지 않고, 새로고침해야 반영되던 문제를 해결했습니다.

Refactor(client): 타임테이블 추가 기능 개선

---

apps/client/src/pages/my/components/artist/no-artist-section.css.ts
apps/client/src/pages/my/components/performance/no-performance-section.css.ts
apps/client/src/pages/performance/components/artist/artist-card.css.ts
apps/client/src/pages/performance/components/button/more-button.css.ts
apps/client/src/pages/performance/components/poster/poster.css.ts
apps/client/src/pages/search/components/artist-info.css.ts
apps/client/src/pages/search/components/artist-not-found.css.ts
apps/client/src/pages/search/components/performance-section.css.ts
apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.css.ts
apps/client/src/pages/time-table/components/calender/calender.css.ts
apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts
apps/client/src/pages/time-table/components/info/info-button.css.ts
apps/client/src/pages/time-table/components/stage/stage.css.ts
apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
apps/client/src/shared/pages/auth/require-login-section.css.ts
apps/client/src/shared/pages/error/error.css.ts
apps/client/src/shared/pages/loading/loading.css.ts
packages/design-system/src/components/artist-card/artist-card.css.ts
packages/design-system/src/components/button/button.css.ts
packages/design-system/src/components/search-bar/search-bar.css.ts
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
packages/design-system/src/components/toast/toast.css.ts
packages/design-system/src/styles/global.css.ts
packages/design-system/src/styles/tokens/display.ts
packages/design-system/src/styles/tokens/overlay.ts

* #317 
display 관련 디자인 토큰에서 불필요한 속성들은 제거를 했어요 
그리고 추가로 토큰 네이밍도 변경했습니다
민하랑 얘기한 후에 
flexCenter
flexAlignCenter
flexColumn
flexColumnCenter 
이 `기존` 속성값들만 유지해도 충분히 거의 대부분의 상황에서 display 관련 속성이 커버가 된다고 판단했어요 나머지를 전부 삭제한 뒤에 between만 추가적으로 유지하였습니다.
그리고 네이밍이 기존에 너무 애매했던 것 같아서 아예 조금 길게 써버렸어요 
예를 들면
flexCenter 에도 alignItems : 'center' 속성이 있고
flexAlignCenter 에도 alignItems : 'center' 속성이 있는데 
flexCenter가 어떤게 Center 라는 거지? 항상 애매해서 
`flexJustifyAlignCenter` 라는 네이밍으로 `justifyContent` 와 `alignItems` 속성이 center 값을 가지고 있는 토큰이라는 것을 명시해보았어요
어차피 토큰은 자동완성이 되니깐 네이밍을 길게 가져가는 것이 더 나을 것 같아서 이런 방법을 사용했어요
기존 토큰 이름들이 변경되느라 변경사항이 좀 많은데 display 쪽 코드만 읽어주시면 돼요

Refactor(design-system): display 디자인 토큰 리팩토링

---

apps/client/package.json
apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.css.ts
apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
apps/client/src/pages/time-table/utils/index.ts
pnpm-lock.yaml

> - #311 
타임테이블 픽셀 밀림 현상 개선
- 타임테이블페이지 테이블 position 계산 로직을 픽셀 단위에서 퍼센트 단위로 수정
- 바닐라익스트렉트 dynamic 의존성 추가
- CSS 변수 관리 방식 개선
기존 코드에서는 타임테이블 아이템의 위치를 픽셀 기반(rem 단위)으로 계산하고 있었습니다. 이로 인해 다음과 같은 문제가 발생했습니다:
1. **환경별 렌더링 불일치**: 크롬/사파리에서 픽셀이 다르게 렌더링되어 테이블이 실제 시간에 맞게 정확히 배치되지 않는 현상 발생
2. **해상도 대응 문제**: 기기 해상도에 따라 테이블의 위치가 밀리는 문제 발생
3. **유지보수 어려움**: 픽셀 단위로 하드코딩된 값들로 인해 변경 시 여러 곳을 수정해야 하는 불편함
1. **퍼센트 기반 계산 방식으로 로직 수정**:
테이블의 position을 픽셀 단위가 아닌 퍼센트 단위로 계산하여 환경에 관계없이 일관된 렌더링 제공
- 기존 방식은 5분에 0.75rem씩 차지하도록 top position을 계산하여 해상도, 환경 차이가 있었음
- 타임테이블보드의 전체 높이를 100%로 잡고 공연 시작 시간과 페스티벌 오픈 시간의 차이를 퍼센트로 계산하여 정확한 위치에 배치
2. **CSS 변수 관리 개선**:
- 인라인 스타일로 직접 정의하던 방식에서 createVar()와 assignInlineVars를 활용한 방식으로 변경하여 변수 관리를 쉽고 용이하도록 개선했습니다. 
```typeScript
// 기존: React.CSSProperties로 인라인 스타일 정의
style={
{ …
```

Refactor(client): 타임테이블 픽셀 밀림 현상 개선

---

apps/client/src/pages/home/page/home.tsx
apps/client/src/pages/performance/components/info/info.tsx
apps/client/src/pages/performance/components/summary/summary.tsx
apps/client/src/pages/search/components/artist-section.tsx
apps/client/src/pages/search/components/performance-info.tsx
apps/client/src/pages/search/components/performance-section.tsx
apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.tsx
apps/client/src/pages/time-table/components/calender/calender.tsx
apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
apps/client/src/pages/time-table/hooks/use-data-formatted.ts
apps/client/src/pages/time-table/types/type-guards.ts
apps/client/src/pages/time-table/utils/index.ts
apps/client/src/shared/utils/use-format-date.ts

* #323 
* 날짜 포맷팅 중앙관리를 위한 유틸 함수 추가
* 타입 가드 함수 추가
날짜 데이터 형식이 서버에서 통일되어 내려오게 되었어요 기존에는 통일되지 않았기에 프론트에서 데이터를 재가공하는데 있어서 거의 동일한 역할을 하는 함수가 도메인별로 존재하는 것이 불필요하다 생각하여 해당 로직을 유틸함수로 관리하기 위해서 데이터 형식을 통일시켜달라고 요청하였어요
역시나 서버에서 데이터 형식을 변경하자마자 타임 테이블, 상세 페이지 검색 페이지, 등등 거의 대부분의 페이지에서 화면이 렌더링 되지 않거나 하는 에러가 발생했고, 서버에 대한 의존도가 매우 높다는 것을 알 수 있었어요
유틸함수로 관리하더라도 서버에서 데이터 형식을 변경한다면 똑같이 에러가 발생하겠지만 중앙에서 관리하기 때문에 중앙에서 로직만 수정해주면 이번 작업과 같이 유지 보수에 많은 리소스가 들지 않을 수 있을 것 같아요.
❗home 상단 캐러셀에는 아직 날짜 포맷팅을 적용시키지 않고 있는데, gui 가 크게 변경되기 때문에 일부로 수정하지 않았습니다. 다음번에 해당 캐러셀 작업하시는 분이 유틸 함수 이용해서 처리해주시면 좋을 것 같아요
💣리뷰로 변경 사항 달아두겠습니다

Refactor(client): 날짜 포맷팅 로직 수정

---

apps/client/src/shared/apis/like/like.ts
apps/client/src/shared/apis/user/user.ts
apps/client/src/shared/constants/api.ts

- #347 
- my 아티스트 미리보기 목록 조회 api url 에 `preview` 가 추가되어서 반영하고, 
- 기존에 artist like post, delete END_POINT도 변경했습니다.

Fix(client): my 아티스트 조회 api url 수정 반영

---

apps/client/src/pages/my/components/performance/performance-list.tsx
apps/client/src/pages/my/components/profile/box.css.ts
apps/client/src/pages/my/components/profile/box.tsx
apps/client/src/pages/my/components/profile/user-info.css.ts
apps/client/src/pages/my/components/upcomingPerformance/no-upcoming-performance-section.css.ts
apps/client/src/pages/my/components/upcomingPerformance/no-upcoming-performance-section.tsx
apps/client/src/pages/my/components/upcomingPerformance/upcoming-performance-section.css.ts
apps/client/src/pages/my/components/upcomingPerformance/upcoming-performance-section.tsx
apps/client/src/pages/my/page/profile/my-profile.tsx
apps/client/src/shared/mocks/performance-data.ts

> - #373
My 페이지 수정된 뷰를 적용했어요.
- UpcomingPerformanceSection 컴포넌트 추가
- NoUpcomingPerformanceSection 컴포넌트 추가
- My페이지 내에 사용되는 컴포넌트 일부 기능 수정
다가오는 공연 관련 컴포넌트 네이밍이 길어지더라도 의미를 확실히 담는게 좋다고 생각해서 
`UpcomingPerformanceSection`, `NoUpcomingPerformanceSection`으로 네이밍 했어요.
참고로 My도메인을 갖는 뷰는 이 PR로 인해서 전부 수정 완료입니다.
핸드오프...🤣 (아 #372  이거 남았네요 ..)

Feat(client): My 페이지 수정된 뷰 적용

---

apps/client/src/pages/onboarding/components/artist-search.css.ts
apps/client/src/pages/onboarding/components/artist-search.tsx
apps/client/src/pages/onboarding/components/artist-select.tsx
apps/client/src/pages/onboarding/components/onboarding-complete.tsx
packages/design-system/src/components/avatar/avatar.css.ts
packages/design-system/src/components/description/description.css.ts

- #376 
- 사용되지 않는 import 혹은 style 파일을 삭제했습니다.
- 애니메이션의 디테일을 수정
- 검색 플로우 구현
- 조건부 렌더링 로직
step 2의 애니메이션을 수정했으나, 더 자세한 요구사항은 QA기간에 반영하겠습니다 
초기에는 useState의 true , false 값으로 ArtistSearch 컴포넌트를 조건부 렌더링 하였으나, 
문제가 발생했어요. SeachBar 컴포넌트에서 사용되는 back 버튼의 기본 동작인 navigate(-1) 이 동작하지 않았는데, 이유는 ArtistSelect 와 ArtistSearch 은 같은 url 값을 갖기 때문에, -1 이 요구대로 동작하지 않았던 거였는데요, 
`?search=true` 쿼리로 url 을 분기하게끔 하였습니다. 쿼리 스트링을 이용해서 총 2가지 문제를 해결할 수 있었는데요,
한 가지는 말씀드린 navigate 동작이고, 한 가지는 사용자가 ArtistSearch 에서 새로고침을 할 경우 상태값이 초기화 되면서 ArtistSelect 컴포넌트로 리렌더링 되는 현상이였습니다. 
남은 작업은 아티스트 정보를 불러오고, post api를 연동하고, 검색 api 를 연동하는 작업입니다.
https://github.com/user-attachments/assets/08fda1b1-1cb0-4b33-99e0-58148b177044

Feat(client): 온보딩 페이지 내 검색 플로우 구현

---

apps/client/src/pages/my/components/artist/artist-list.tsx
apps/client/src/pages/my/hooks/use-my-favorites.ts
apps/client/src/pages/my/page/artist/artist-more.tsx
apps/client/src/pages/my/page/performance/performance-more.tsx
apps/client/src/pages/my/page/profile/my-profile.tsx
apps/client/src/shared/apis/user/user-queries.ts
apps/client/src/shared/apis/user/user.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/user-response.ts
apps/client/src/shared/utils/format-date.ts
packages/design-system/src/components/like-button/like-button.css.ts
packages/design-system/src/components/like-button/like-button.tsx

> - #391 
My artist 전체 목록 조회 API를 연결했어요.
- My artist 전체 목록 조회 API 연결
- 아티스트 추가 날짜를 포맷하는 유틸함수 추가
- 좋아요 버튼 개선
기존에는 좋아요버튼 애니메이션(scale transform)이 초기 페이지 렌더링시에도 적용이됐어요.
딱히 상관이 없을 것 같아서 그냥 두었는데, 아티스트 목록에 정렬 기능이 생기고나니 정렬이 된 컴포넌트의 좋아요 버튼만 DOM에서 수정되어 애니메이션이 적용되는 현상이 발생했습니다... 매우 어색하더라구요.
그래서 렌더링마다 애니메이션이 발생하는 대신 '좋아요' 클릭 시에만 애니메이션이 실행되도록 별도의 animate 상태 값을 추가하고, CSS에서 애니메이션 속성을 liked 상태와 분리하여 animate가 true일 때만 애니메이션이 적용되도록 변경했어요.

Feat(client): My artist 전체 목록 조회 API 연결

---

apps/client/src/App.tsx
apps/client/src/pages/home/page/home.tsx
apps/client/src/pages/login/hooks/use-social-login-mutation.ts
apps/client/src/pages/login/page/login.tsx
apps/client/src/pages/my/components/profile/logout-section.tsx
apps/client/src/pages/my/hooks/use-logout.ts
apps/client/src/shared/apis/auth/auth.ts
apps/client/src/shared/apis/carousel/performances.ts
apps/client/src/shared/apis/carousel/ticketing.ts
apps/client/src/shared/apis/confeti-detail/performance.ts
apps/client/src/shared/apis/config/instance.ts
apps/client/src/shared/apis/config/interceptor.ts
apps/client/src/shared/apis/onboard/artist-related-keywords.ts
apps/client/src/shared/apis/onboard/top-artist.ts
apps/client/src/shared/apis/search/search.ts
apps/client/src/shared/constants/api.ts
packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #395
로그인 여부에 따른 API 호출 방식을 수정했어요.
- 환경변수 사용 CONFIG 객체로 통일
- 로그인 여부에 따른 API 호출 방식 수정
환경변수 관리를 일관된 방식으로 개선하기 위해, 개별적으로 사용하던 `import.meta.env` 접근을 `CONFIG` 객체로 통합했어요.
`as string` 처리로 타입 오류 방지하고, 자동완성 기능으로 휴먼에러를 감소시킬 수 있을 것이라 생각해요.
기존에 언급되었던 `axiosInstance`와 `axiosPublicInstance`의 분리 사용 문제를 해결했어요.
로그인 여부에 따라 `Authorization` 헤더를 조건부로 추가하도록 `handleCheckAndSetToken`을 개선하여, 모든 요청을 하나의 `axiosInstance`로 처리할 수 있게 만들었어요.
기존에는 로그인하지 않은 사용자의 요청을 위해 `axiosPublicInstance`를 따로 사용했지만, 이 방식에는 다음과 같은 문제점이 있어요.
- **반환 형식 불일치**
`axiosInstance`는 `res.data`를 반환하는 반면(한 번더 추상화된 메서드 사용)
`axiosPublicInstance`는 `res.data.data`를 반환하여 응답 파싱 방식이 다름
- **중복 관리**
두 인스턴스를 병행해서 사용하면서 공통적인 설정이나 에러 처리 로직을 중복 구현해야함.
그래서...
인터셉터 레벨에서 `ACCESS_TOKEN_KEY` 존재 여부를 판단해 `Authorization` 헤더를 조건부로 추가했어요.
이를 통해 로그인 여부와 관계없이 …

Feat(client): 로그인 여부에 따른 API 호출 방식 수정

---

apps/client/src/pages/onboarding/hooks/use-onboard.ts
apps/client/src/pages/onboarding/page/onboarding.tsx
apps/client/src/shared/apis/onboard/auth-onboard.ts
apps/client/src/shared/constants/api.ts

- #405 
- 버튼 text '다음'으로 변경
- 유저가 하나 이상의 선호 아티스트를 선택해야 하는 요구사항 반영했습니다.
- post api 연동하였습니다.
onboard 페이지 컴포넌트에 상태 업데이트 및 리패칭 하는 함수들이 존재합니다.  페이지와 분리하기 애매하다고 생각하여 최대한 책임을 분리한 후에 onboard 컴포넌트 내부에 두었는데 좋은 아이디어가 있으면 말씀해주세요.
그리고 기획이 제시해준 요구사항에는 유저가 한명 이상의 아티스트를 선택해야 버튼이 활성화 된다고 명시 되어 있어서 반영하였으나, 서버에서 설계한 api 에서는 `2`개 이하일 때 400 에러를 반환하고 있기에 슬랙을 통해 api 수정 요청 드렸습니다.
그리고 use-onboard 에 있는 tsdoc 주석을 제거하였는데 로직이 비교적 단순하고, 네이밍도 직관적으로 설계되어 있다고 판단하여 오히려 주석이 가독성을 해치는 느낌이라 제거하였습니다

Feat(client): 온보딩 페이지 auth/onboard post api 연동

---

apps/client/src/pages/search/components/search-result/performance/performance-info.tsx
apps/client/src/pages/search/components/search-result/performance/performance-section.tsx
apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/page/search-page.tsx
apps/client/src/pages/search/page/search-result-page.tsx
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/apis/search/search.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/search-reponse.ts

> - #418 
요청 공연 타입 분석 및 예정된 공연 목록 조회 API를 연동했어요.
- 요청 공연 타입 분석 API 연동
- 예정된 공연 목록 조회 API를 연동
요청 공연 타입 분석 API를 연동하여, 사용자가 검색했을때 키워드랑 공연타입을 분석해요.
그리고 해당 결과를 통해 예정된 공연 목록 조회 API를 호출합니다.
예정된 공연 목록 조회 API의 케이스가 3가지가 있는데, 현재 첫번째 케이스 (아티스트 검색) 부분만 구현된 상태입니다.
그래서 공연 단독 조회는 현재 안됩니다.
공연 단독 조회를 하려면 기존 로직에서 수정해야할게 백만가지가 넘어서 막막합니다.

Feat(client): 요청 공연 타입 분석 및 예정된 공연 목록 조회 API 연동

---

apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
apps/client/src/pages/my-history/components/preview/preview-section.tsx
apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.css.ts
apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
apps/client/src/pages/my-history/page/hooks/use-performance-search.ts
apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/page/search-page.tsx
apps/client/src/shared/apis/my-history/setlist-queries.ts
apps/client/src/shared/apis/my-history/setlist.ts
apps/client/src/shared/constants/path.ts
apps/client/src/shared/hooks/use-related-search.ts
apps/client/src/shared/router/lazy.ts
apps/client/src/shared/router/router.tsx
apps/client/src/shared/types/my-history-response.ts
apps/client/src/shared/types/search-reponse.ts
packages/design-system/src/components/search-suggestion-list/search-suggestion-list.tsx

> - #427 
셋리스트 공연추가 페이지를 제작하고, 공연 추가를 위한 공연 검색 API를 연동했어요.
- 셋리스트 공연추가 페이지 뷰 제작
- 공연 추가를 위한 공연 검색 API 연동
- 연관검색어 처리 훅 shared 파일로 분리
코드가 많이 더러운데, 정말 바빠서 죄송합니다...
리소스가 많이 부족하네요. 페이지 구조는 기존 검색페이지와 비슷한 형식입니다.
커스텀 훅으로 로직을 분리하지 않은 이유는 반드시 리팩토링이 필요하다고 생각했고, 스프린트 끝나면 검색로직에서 공통 부분을 빼서 커스텀 훅으로 제작하기 위함입니다.

Feat(client): 셋리스트 공연추가 페이지 제작 및 조회 API 연동

---

apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
apps/client/src/pages/my-history/components/preview/preview-section.tsx
apps/client/src/pages/my-history/hooks/use-add-performance-mutation.ts
apps/client/src/pages/my-history/page/record/my-record.tsx
apps/client/src/shared/apis/my-history/my-history.ts
apps/client/src/shared/apis/my-history/setlist.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/my-history-response.ts

> - #429 
셋리스트 공연 추가 API를 연동했어요.
- 셋리스트 공연 추가 API 연동
주석으로 적어두긴했는데
셋리스트에 공연을 추가할 때 1개 추가, 여러개 추가시 네비게이션 요구사항이 달라요.
- 1개 추가 -> 해당 공연의 셋리스트 페이지로 이동
- 여러개 추가 -> 셋리스트 초기 페이지로 이동(현재 적용상태)
셋리스트 상세페이지가 나오면 연동 부탁드려요. (1개 추가 case)

Feat(client): 셋리스트 공연 추가 API 연동

---

apps/client/src/shared/apis/config/interceptor.ts

> - #440 
토큰 재발급 로직을 수정했어요.
- 토큰 재발급 로직을 수정
원인 1. 404인 경우에도 불필요한 토큰 재발급이 발생했음.
-> 401일 경우에만 재발급 받도록 수정
원인 2. 토큰 재발급시에 기존 인터셉터가 적용된 axiosInstance를 사용함. 그래서 헤더에 refreshToken이 아닌 accessToken이 넘어갔음.
-> fetch 사용하도록 수정

Fix(client): 토큰 재발급 로직 수정

---

apps/client/src/pages/performance/components/expanded/expanded-section.css.ts
apps/client/src/pages/performance/components/expanded/expanded-section.tsx

- #475 
- 더보기 버튼 클릭 시 끊기는 애니메이션 ux를 개선하였음
기존에는 scrollHeight를 사용해서 height를 계산하고 직접 스타일에 적용하는 방식이었어요 이 방식이 더보기가 동작할 떄 애니메이션이 끊기는 현상이 발생한건데, 
max-height , opacity, padding에 css 트랜지션을 적용하는 방식으로 구조를 변경하였어요
useRef, useEffect , useState를 제거했고, max-height와 opacity를 이용해서 구현하였습니다. 
https://github.com/user-attachments/assets/fedb14da-d0c5-4c52-b6b8-6ce41c03e17c
https://github.com/user-attachments/assets/61f72a48-34cb-46fa-bde2-4eb95afcbd64

Refactor(design-system): 아티스트 더보기 UX개선

---

apps/client/src/pages/time-table/components/time-table-board/time-cell.css.ts
apps/client/src/pages/time-table/components/time-table-board/time-table-item.css.ts
apps/client/src/pages/time-table/components/time-table-board/time-table-item.tsx
apps/client/src/pages/time-table/utils/index.ts

> - #482
- 타임테이블 보드 레이아웃 수정
<table>
<tr>
<td>
<strong>전</strong><br />
</td>
<td>
<strong>후</strong><br />
</td>
</tr>
</table>

Fix(client): 타임테이블 보드 레이아웃 수정

---

apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts

- #489 
- 모바일에서 position 이 absolute로 잡혀있어서 뷰가 무너지는 현상을 고쳤어요

Fix(client): empty-festival 컴포넌트 뷰 수정

---

packages/design-system/src/components/music-item/music-item.css.ts

- #492 
textOverflow: 'ellipsis' 가 설정되어있지만, max-width값이 없어서 적용이 안되고 있었어요 해당 사항 변경해서 적용합니다.
전
후

Fix(design-system): 음악 아이템 제목의 최대 너비 및 너비 설정 추가

---

packages/design-system/src/components/music-item/music-item.css.ts

- #500 
- 홈 페이지에 있는 음악 리스트에서 가수명이 길어질 경우 스크롤 밖으로 나가는 현상을 수정합니다.
- max-width는 피그마 기준으로 설정했고, width를 100%로 주어서 문제해결했어요
https://github.com/user-attachments/assets/dfc8c2d9-5588-4c67-8b95-6a9f31d61dd5

Fix(design-system): (QA/5) 음악 아이템 아티스트 제목의 최대 너비 및 너비 설정 추가

---

apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
apps/client/src/pages/my-history/components/record/record-info.tsx
apps/client/src/pages/my-history/components/record/record-introduce.tsx
apps/client/src/pages/my/components/profile/user-info.css.ts
apps/client/src/pages/my/components/profile/user-info.tsx
apps/client/src/pages/onboarding/components/artist-select.css.ts
apps/client/src/pages/performance/components/reservation/reservation.css.ts
apps/client/src/pages/time-table/page/delete-festival/delete-festival-dialogs.tsx
packages/design-system/src/components/avatar/avatar.css.ts
packages/design-system/src/components/avatar/avatar.tsx
packages/design-system/src/components/footer/footer.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.css.ts

> - #514 
다른 파트의 확인이 필요한 UI 이슈 QA 말고는 다 해놓았습니다! 셋리스트 관련 ui는 어떤 공연을 추가해도 저주에 걸려버려서 확인을 할 수가 없네요
- 프로필 수정 터치 영역 늘림
- 내 공연 > 콘페티 기록 부분에서 프로필 사진 체크 안 되게 수정
- 온보딩, 내 공연 검색 아래 여백 추가 (자체 QA 진행 ^^,,, 수진이한테 오마카세 진행하고 컨펌받음)
- 예매처 바로가기 이미지 확대 (스크린샷은 슬랙에서 확인)
- 타임테이블 라이팅 (명-> 개) 수정
- 홈 > performance 캐러셀 커서 pointer 적용
- 타임테이블 삭제 모달 숫자와 개 사이에 공백 추가
- 푸터 이용약관, 개인정보처리방침 링크 이동
1. 내 공연 - 콘페티 기록에서 프로필 Avatar 컴포넌트의 체크가 비활성화되도록 수정하면서 해당 상태에서 cursor가 여전히 pointer로 표시되는 UX 흐름이 어색하다고 판단되어 cursor 스타일도 함께 제어되도록 Avatar 컴포넌트를 수정했습니다.
2. 내 공연 검색 섹션에서 버튼과 제목이 겹치는 이슈가 있어 하단 여백을 추가하여 분리되도록 수정했습니다. 온보딩 화면에서도 아티스트 이름과 버튼 사이가 붙어 있어 답답한 느낌이 있길래... 아래 여백 추가했습니다! 
3. YES24 예매처가 배포된 사이트에서는 좌우 여백이 보이더라구요. 확대한 후에도 그러는지는 배포 후에 테스트 해보겠습니다 🥲
4. 이 PR에 마이페이지 쪼잔 qa도 해서 넣을게요 저녁에...
<table>
<tr>
<td><img …

Feat(client): UI 관련 QA 반영

---

apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
apps/client/src/pages/my-history/components/preview/preview-section.tsx
apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
apps/client/src/shared/router/path.ts
apps/client/src/shared/types/my-history-response.ts
packages/design-system/src/components/festival-card/festival-card.tsx

> - #517 
내 공연 페이지에서 발생하는 버그들을 수정했어요.
- My 타임테이블내 FestivalCard 클릭시 타임테이블 페이지로 이동
- My 셋리스트내 FestivalCard 클릭시 셋리스트 상세 페이지로 이동
- 내 공연 검색후 공연 추가시 type이 고정되어있는 문제 해결
- 중첩라우팅으로 인해 내 공연에서 buildPath가 제대로 작동하지 않는 문제 해결
- path.ts내에 절대경로를 추가로 생성해서 해결했어요. 더 나은 방법이 있다면 제안해주세요 !
내 공연 페이지의 해당 섹션들과 
해당 페이지들이 동일한 UI를 공유하지만 내부 로직은 조금 달라요. (라우팅 되는 부분, 데이터, ...)
그래서 조건부로 분리를 하는 방식으로 구현이 되어있는데 이게 맞는지 의문이 드네요. 같은 UI를 공유하지만 각 페이지 내에서 요구사항이 변경된다면 또 조건부로 구현을 해줘야한다는 문제가 생길 수 있어요.
의견을 받겠습니다!!!
---
추가로 
여기 FestivalCard로 클릭을하면 타임테이블 페이지로 이동을 하도록 수정은 했는데, 포커스가 항상 첫번째로 맞춰진다는 이슈가 있어요. 이걸 그냥 두는게 좋을지 해결을 하는게 좋을지도 의견이 궁금합니다.

Fix(client): 내 공연 관련 버그 수정

---

apps/client/src/pages/time-table/constants/index.ts
apps/client/src/pages/time-table/page/add-festival/add-festival.tsx

- #527 
- 페스티벌의 추가 갯수를 3개 -> 5개로 수정합니다.
- toast 이벤트 트리거가 기존에는 '추가하기' 버튼을 클릭했을 때 동작하였는데, 이 부분을 '페스티벌 카드의 클릭' 으로 변경합니다
- 버튼의 disabled 되는 조건이 하나 더 증가했어요 
```tsx
const isButtonDisabled =
selectedFestivals.length === 0 || TOTAL_SELECTIONS >= MAX_SELECTIONS;
```
초기에는 당연히 
```tsx
const handleFestivalClick = (festivalId: number, isSelected: boolean) => {
if (isSelected) {
removeSelect(festivalId);
} else {
addSelect(festivalId);
}
};
```
이 핸들러 함수에서 클릭 되어있는(isSelected) 한 카드의 갯수가 max 보다 크거나 같아면 showToast 를 호출하면 된다고 생각했어요. 근데 React의 상태 업데이트의 특징을 고려하지 못했어요 `selectedFestivals` 가 setState 직후에 즉시 반영되지 않기 때문에 해제 클릭 시에도 조건이 맞아 toast 가 잘못 실행되는 문제가 발생했어요.
이를 해결하기 위해 **상태 변경을 감지하는 useEffect** 로 toast 트리거를 이동했습니다.
```tsx
useEffect(() => {
if (TOTAL_SELECTIONS >= MAX_SELECTIONS) {
showToast();
}
}, …
```

Fix(client): 페스티벌 추가 갯수 수정 및 toast 이벤트 수정

---

apps/client/src/pages/home/components/suggest-music-section.tsx
apps/client/src/shared/hooks/use-music-player.ts

- #536 
- 다른 노래 더보기 버튼 클릭 시 음악 재생 일시정지  
노래 재생 중 사용자가 다른 노래 더보기 버튼을 클릭하면 기존에는 노래가 계속 재생되었는데, 재생되지 않아야 더 자연스러운 경험이라고 생각해서 이 부분 수정했습니다 . 
기획파트랑 얘기 된 부분입니다. 
[슬랙 스레드](https://weareconfeti.slack.com/archives/C08JK2MUDV3/p1748360340414689)
audioRef 를 통해 직접 제어할 수도 있었지만, 재생 중지 로직의 명확한 책임 분리를 위해 별도의 audioStop 핸들러 함수를 정의했어요

Feat(client): 추천 음악 정지 기능 추가 

---

apps/client/src/pages/timetable/components/calender/calender.tsx
apps/client/src/pages/timetable/components/festival-selector/festival-button.css.ts
apps/client/src/pages/timetable/components/festival-selector/festival-button.tsx
apps/client/src/pages/timetable/components/timetable-board/booth-open-box.css.ts
apps/client/src/pages/timetable/components/timetable-board/time-cell.css.ts
apps/client/src/pages/timetable/components/timetable-board/timetable-board.css.ts
apps/client/src/pages/timetable/components/timetable-board/timetable-item.css.ts
apps/client/src/pages/timetable/components/timetable-board/timetable-item.tsx
apps/client/src/pages/timetable/constants/index.ts
apps/client/src/pages/timetable/hooks/use-data-formatted.ts
apps/client/src/pages/timetable/page/timetable-content/timetable-content.tsx
apps/client/src/pages/timetable/page/timetable-page.tsx
apps/client/src/pages/timetable/utils/index.ts

> - #560 
- timetableBoard layout 픽셀 단위 모두 rem -> px로 변경
- 날짜 선택 변경에 따라 알맞은 타임테이블 렌더링하도록 수정
- 정말 한치 오차도 없이 정확하게 하려면 px로 변경하는 수밖에 없었어요 rem으로 하면 저번에 qa 잡힌 것처럼 조금씩 오차가 생기더라구요. 
- px로 변경하면서, 1분당 1.5px로 계산하고 있어 미세한 단위라 그런지 확대/축소 시 위치가 조금씩 어긋나고 있어요...
일단 화면 100% 비율일때를 기준으로 정확하게 맞춘거라... 이부분 어떻게 해야할 지 아직 고민중입니다. (곡추가 검색 해결하고 다시 살펴볼게요)
- 날짜 변경 시 타임테이블 알맞게 렌더링되도록 수정했습니다!
이전 pr 리베이스 해줬더니 변경사항이 너무 많이 잡혀서 새로 올립니다ㅜㅜ
- 무대 2개일 때
- 무대 3개일 때
- 무대 4개일 때

Fix(client): 타임테이블 오류 해결

---

apps/client/src/pages/home/components/category-tabs.css.ts
apps/client/src/pages/home/components/category-tabs.tsx
apps/client/src/pages/home/constants/menu.ts
apps/client/src/pages/home/constants/tab.ts
apps/client/src/pages/home/hooks/use-active-section.ts
apps/client/src/pages/home/page/home-page.tsx
apps/client/src/pages/my-history/page/my-history.tsx
apps/client/src/pages/my/page/setting/setting.css.ts
apps/client/src/pages/onboarding/components/artist-select.css.ts
apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
apps/client/src/pages/timetable/page/timetable-layout.tsx
apps/client/src/shared/components/navigation-tabs.tsx
packages/design-system/src/components/header/header.css.ts
packages/design-system/src/styles/theme.css.ts
packages/design-system/src/styles/tokens/size.ts

> - #609 
홈페이지 내 Chip 카테고리를 스크롤에 따라 상단에 고정했어요.
- 스크롤에 따라 Chip 컴포넌트 상단 고정
- size 디자인 토큰 추가
많은 css 파일에서 헤더 높이를 계산해서 스타일링을 하는 경우가 많더라구요 (5.4rem)
css내 의미를 알 수 없는 숫자들도 매직넘버와 같은 문제점을 가지고 있다 생각했어요.
추후에 헤더 크기가 바뀐다거나 하면 모든 파일에서 찾아 수정해야 하는 일이 발생할 수 있기에 디자인 토큰으로 지정해두었어요.
앞으로 재사용될 size(width, height, ..)는 디자인 토큰에 지정해주세요!
https://github.com/user-attachments/assets/a57f9609-a79c-4364-bae7-df2c801463b2

Feat(client): 홈페이지 Chip 카테고리 상단 고정

---

.github/workflows/ci.yml

> - #637 
CI 환경 내 TurboRepo 캐시 액션을 추가하여 빌드 속도를 개선해요.
- rharkor/caching-for-turbo 액션 추가
기존 CI 환경에서는 pnpm 의존성 캐시만 저장했는데, 
TurboRepo 빌드 캐시를 추가하여 빌드시 불필요한 작업을 줄이고 시간을 단축시킬 수 있을거라 기대합니다!
GitHub Actions 내에서 터보레포의 로컬 캐시 서버를 시뮬레이션하는 오픈소스 액션을 도입해, [Vercel](https://turborepo.com/docs/core-concepts/remote-caching#vercel) remote cache 없이도 TurboRepo 캐시를 활용할 수 있도록 설정했어요.
ref) [Caching for Turborepo with GitHub Actions
](https://github.com/marketplace/actions/caching-for-turborepo)

Feat: CI 환경 내 TurboRepo 캐시 액션 추가

---

apps/client/src/pages/onboarding/hooks/use-onboard-mutation.ts
apps/client/src/shared/apis/auth/auth-mutation.ts
apps/client/src/shared/constants/api.ts

> - #646 
- 온보딩 후 토큰 재발급 로직 수정 
c0a15ca5c9b00d61cb8069b21bc788f70116ead7 급하게 개발하느랴 바로 develop에 넣었는데 해당 부분 수정해서 다시 올려요.
```ts
// 기존 구현 방식
export const postReissueToken = async (): Promise<void> => {
const refreshToken = getRefreshToken();
try {
const response = await authPost<BaseResponse<TokenResponse>>(
END_POINT.POST_REISSUE_TOKEN,
{},
{ headers: { Authorization: `Bearer ${refreshToken}` } },
);
const { accessToken, refreshToken: newRefreshToken } = response.data;
authTokenHandler('set', accessToken, newRefreshToken);
} catch (error) {
if (error instanceof HTTPError) {
throw error;
}
throw new HTTPError(
HTTP_STATUS_CODE.UNAUTHORIZED,
'토큰 재발급에 실패했습니다.',
);
}
};
```
기존 작업했던 방식에서는 postReissueToken이 많은 역할을 담당하고 있다고 판단해서 SRP 원칙에 따라 역할을 분리시켰어요.
```ts
// 수정 방식
export const postReissueToken = …
```

Refactor(client): 토큰 재발급 로직 수정

---

apps/client/src/shared/router/routes/layout-free-routes.tsx

- #651 
-  온보딩 에러바운더리 분리
온보딩 페이지의 에러바운더리를 별도로 분리했어요. 온보딩 과정 중 에러가 발생했을 때, home 이 아닌 onboarding 으로 리다이렉트 되도록 설정했어요.
기존 에러바운더리를 유지할 경우 에러가 발생했을 때 일반 유저가 다시 onboarding 으로 접근할 진입점이 존재하지 않기에.  리다이렉트 url 을 재설정 할 수 있도록했어요
https://weareconfeti.slack.com/archives/C08JX8QTCCR/p1755310274455629

Feat(client): 온보딩 페이지 에러바운더리 분리

---

apps/client/src/pages/my/hooks/use-edit-profile.ts
apps/client/src/pages/my/page/edit/edit-profile.tsx
apps/client/src/shared/apis/user/user-mutations.ts

> - #654 
프로필 편집 페이지 로직을 개선했어요.
- 프로필 사진 변경없이 요청을 보내는 경우 이미지가 사라지던 버그 해결
- useEditProfile커스텀 훅 제작
- API 레이어(페칭함수-patchUserInfo)내 FormData생성 로직 분리
기존에는 업로드할 파일(이미지), 기존 이미지, 이름 등 복잡한 상태관리를 여러개의 state로 관리하고 있었는데,
이를 useReducer로 통합했어요. 가독성 측면에서 더 괜찮은 방법이라고 생각했어요.

Refactor(client): 프로필 편집 페이지 개선
