.eslintrc.cjs

> - #7 
root 환경에서 eslint 속성 추가했습니다. 
Mac OS 와 WIndow 와의 줄 바꿈 스타일 차이가 존재해서 OS에 맞는 줄바꿈 스타일을 자동으로 적용해주는 lint 속성 추가했습니다.
```
module.exports = {
'prettier/prettier': ['error', { endOfLine: 'auto'} ],
}
```
* `auto` 설정은 운영 체제에 맞는 줄바꿈 스타일을 자동으로 선택하게 만들어주는 것
2025 첫 PR 새해 복 많이받으세요😂👩‍🦲

Chore: root 환경 eslint 속성 추가

---

.github/workflows/discord-notify.yml

* #10 
디스코드에 PR 생성 시, 병합 시에 알림을 주기 위해서
.github/workflow/discord-notify.yml 파일 생성하고 작성했습니다.
* 레포지토리에 new secret 생성했습니다.
* .github/workflow/discord-notify.yml 파일 생성하고 작성했습니다.
이제 PR 생성 및, 병합 시에 디스코드 WEB채널 깃허브-웹 채널에 알림전송됩니다. 추가적으로 필요한 이벤트 트리거 있으면 말씀해주세요
올바른 코드리뷰 문화의 정착을 위해....👧

Chore: discord 알림 .yml 파일 생성

---

.github/workflows/build-test.yml
.github/workflows/discord-notify.yml
.github/workflows/sync.yml
pnpm-lock.yaml

> 관련 있는 Issue를 태그해주세요. (e.g. > - #100)
- #25 
- ci cd 워크플로우 세팅했습니다.

Init: ci cd 워크플로우 세팅

---

.github/workflows/sync.yml

Refactor: sync.yml 파일 수정

---

.github/workflows/sync.yml

> 관련 있는 Issue를 태그해주세요. (e.g. > - #100)
- sync yml 파일 수정했습니다

Chore: sync 업데이트

---

.eslintrc.cjs

* 삭제되지 않은 gitkeep 등 불필요한 파일 및 코드 삭제합니다

Delete: 필요없는 파일, rules 삭제

---

packages/design-system/src/styles/global.css.ts

Refactor: global style 모바일 뷰 수정

---

packages/design-system/src/styles/tokens/font-styles.css.ts
packages/design-system/src/styles/tokens/typography.css.ts

- #52
- `typography.css` line-height 값 추가
- `font-styles.css` line-height 값 변경
저희 Style 관련 라벨이 사라져있길래 우선 다시 추가해놓았습니다...
저희 커밋 메시지 컨벤션에선 `style`이 코드 포맷팅 / `design`이 css 수정이라고 알고 있는데 라벨링은 css 관련도 모두 style로 달면 되나요? 관련해서 이야기를 나눴던 것 같은데 기억이 잘...^^

Feat: 타이포 토큰 및 폰트 스타일 업데이트

---

packages/design-system/src/components/index.ts
packages/design-system/src/components/spacing/spacing.css.ts
packages/design-system/src/components/spacing/spacing.stories.tsx
packages/design-system/src/components/spacing/spacing.tsx

> - #71 
spacing 컴포넌트를 추가했어요.
- spacing 컴포넌트 추가
```tsx
<Spacing size='xl' color='white' />
```
해당 방식으로 사용할 수 있어요 default는 md, gray 입니다 !
📸 Screenshot

Feat(design-system): spacing 컴포넌트 추가

---

packages/design-system/src/components/artist-card/artist-card.stories.tsx
packages/design-system/src/components/button/button.stories.tsx
packages/design-system/src/components/button/button.tsx
packages/design-system/src/components/festival-card/festival-card.stories.tsx
packages/design-system/src/components/toast/toast.css.ts
packages/design-system/src/components/toast/toast.stories.tsx

> - #99 
일부 스토리북을 수정했어요
- 토스트 스토리북 레이아웃 수정
- 버튼 스토리북 props 추가
- 카드 스토리북 폴더링 Card/ArtistCard, Card/FestivalCard

Refactor(design-system): 스토리북 수정

---

apps/client/src/App.tsx
apps/client/src/pages/home/page/home.css.ts
apps/client/src/pages/home/page/home.tsx
packages/design-system/src/components/top-carousel/top-carousel.tsx
packages/design-system/src/styles/global.css.ts

> - #98 
홈 화면 상단배너(캐러셀) 추가시 레이아웃이 의도치않게 변경되는 현상을 글로벌 스타일 수정을 통해 해결했어요.
- 글로벌 스타일 수정
- 상단배너 arrow 변경
글로벌 스타일이 일부 변경되었어요. App.tsx내에 rootStyle을 제거하고 #root 스타일을 `globalStyle`에 적용했어요. 
`html, body`에 `width 100%`를 적용했어요.

Fix(client): 글로벌 스타일 수정

---

apps/client/vite.config.ts

> - #107 
vite 서버 호스트 설정을 추가했어요
- vite 서버 호스트 설정을 추가했어요
루트 디렉토리에서 실행해도 모바일 내에서 localhost로 확인할 수 있습니다 !
같은 와이파이에 접속해있으면 모바일로 확인 가능합니다 !

Feat(client): vite 서버 호스트 설정 추가

---

apps/client/src/pages/confeti/components/summary.tsx
apps/client/src/pages/confeti/mocks/confeti-detail.ts
apps/client/src/pages/confeti/page/concert-detail.tsx
apps/client/src/pages/confeti/page/festival-detail.tsx

- #94
- 퍼블리싱 작업은 이미 완료된 상태라 추가적으로 isFavorite 값을 받아 하트 색상을 변경하는 기능만 구현하였습니다.

Feat(client): 공연 상세보기 퍼블리싱

---

apps/client/src/pages/my/components/confeti/conteti-section.tsx
apps/client/src/pages/my/page/confeti/confeti-detail.tsx
apps/client/src/pages/time-table/page/add-festival.tsx
apps/client/src/shared/mocks/performance-data.ts
packages/design-system/.storybook/preview.tsx
packages/design-system/src/components/artist-card/artist-card.stories.tsx
packages/design-system/src/components/artist-card/artist-card.tsx
packages/design-system/src/components/festival-card/festival-card.css.ts
packages/design-system/src/components/festival-card/festival-card.tsx
packages/design-system/src/components/header/header.stories.tsx

> - #105 
- 마이페이지에서 공연 클릭시 ID에 따라 상세 페이지로 이동하도록 라우팅 연결했습니다.
https://github.com/user-attachments/assets/cc67538c-79e4-4475-893f-77fa174fe464

Feat(client): 마이페이지에서 공연 클릭시 detail 페이지 라우팅 연결

---

packages/design-system/src/components/header/header.css.ts
packages/design-system/src/components/navigation/navigation.css.ts
packages/design-system/src/styles/tokens/z-index.ts

> - #155 
헤더가 상단에 고정이 안되는 이슈를 해결했어요.
- default Header position 추가
- Navigation, detail Header 마진 속성 추가

Feat(design-system): 헤더 상단 고정 기능 추가

---

apps/client/index.html

> - #154
op태그를 설정했습니다.
- og태그 설정

Feat(client): og태그 설정

---

apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
apps/client/src/pages/time-table/page/time-table.tsx

> - #185 
EditFloatingButton 웹에서 우측하단 고정안되는 이슈 해결
- EditFloatingButton 미디어 쿼리 추가

Fix(client): EditFloatingButton 웹에서 우측하단 고정안되는 이슈 해결

---

apps/client/package.json
apps/client/src/shared/constants/api.ts
apps/client/src/shared/constants/path.ts
apps/client/src/shared/pages/error/error.tsx
apps/client/src/shared/router/global-layout.tsx
apps/client/src/shared/router/lazy.ts
apps/client/src/shared/router/router.tsx
pnpm-lock.yaml

* #150 
* 에러바운더리 설정했고, 잘못된 url 접근할 경우에 ErrorPage를 보여줄 수 있게끔 설정했습니다. 
변경사항만 확인해주세요!

Feat(client): 에러 페이지 및 레이아웃 추가, react-error-boundary 통합

---

packages/design-system/src/components/artist-card/artist-card.css.ts

> - #222 
아티스트 이미지 깨짐 현상 해결
- 아티스트 이미지내 aspectRatio 속성 추가

Fix(design-system): 아티스트 이미지 깨짐 현상 해결

---

apps/client/src/pages/confeti/components/summary/summary.css.ts
apps/client/src/pages/confeti/components/summary/summary.tsx
apps/client/src/pages/search/components/artist-info.css.ts
apps/client/src/pages/search/components/artist-info.tsx
packages/design-system/src/components/index.ts
packages/design-system/src/components/like-button/like-button.css.ts
packages/design-system/src/components/like-button/like-button.stories.tsx
packages/design-system/src/components/like-button/like-button.tsx

> - #226
LikeButton 컴포넌트 추가
- design-system내 LikeButton 공통 컴포넌트를 추가했고 사용 컴포넌트에 적용했어요.
- 좋아요 버튼 애니메이션 추가

Feat(design-system): LikeButton 컴포넌트 추가

---

apps/client/src/pages/time-table/page/add-festival.tsx

- #213 
- 이미 추가된 페스티벌의 개수까지 포함해서 3개로 제한되게 수정하였습니다.
https://github.com/user-attachments/assets/bd1e41cf-b15f-41bb-9d78-fe9ac7c96b85

Fix(client): 페스티벌 토스트 기능 수정

---

apps/client/src/pages/search/components/artist-info.tsx
apps/client/src/shared/router/protected-route.tsx
apps/client/src/shared/utils/check-is-not-logged-in.ts
packages/design-system/src/components/like-button/like-button.tsx

- #215
- 비로그인일 경우에 서치 페이지의 아티스트 좋아요 누르면 '로그인 후 이용 가능해요' 토스트 뜨게 구현
https://github.com/user-attachments/assets/2d6a5232-d3a5-48e2-a0fb-5863231450bd

Feat(client): 비로그인 상태로 좋아요 클릭시 토스트 출력 추가

---

apps/client/src/pages/time-table/components/stage/stage.tsx
apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
apps/client/src/pages/time-table/constants/index.ts

> - #230 
타임테이블 레이아웃 수정
- 타임테이블 레이아웃 수정

Refactor: 타임테이블 레이아웃 수정

---

apps/client/vercel.json

vercel.json파일 추가
- vercel.json파일 추가
<!--

Deploy: vercel.json파일 추가

---

apps/client/src/pages/confeti/components/poster/poster.css.ts

> - #235 
상세페이지 내 포스터의 border-radius를 수정했습니다.
- 상세페이지 내 포스터 border-radius 수정

Fix(client): (QA/2) 포스터 border-radius 수정

---

apps/client/src/shared/pages/error/error.css.ts
packages/design-system/src/components/performance-carousel/dots.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.tsx
packages/design-system/src/components/performance-carousel/slick.css.ts
packages/design-system/src/styles/tokens/font-styles.ts
packages/design-system/src/styles/tokens/typography.ts

> - #233 
-  메인페이지 배너 상단 수정, 404 페이지 글자 크기 변경

Fix(design-system): 메인페이지 배너 상단 수정, 404 페이지 글자 크기 변경

---

apps/client/src/pages/home/page/home.tsx
apps/client/src/shared/mocks/performance-data.ts
packages/design-system/src/components/like-button/like-button.css.ts

> - #236 
유저 및 페스티벌 데이터 수정
- 유저 데이터 실제 데이터로 수정
- 페스티벌 데이터 수정
- 좋아요버튼 애니메이션 조정

Fix(client): 유저 및 페스티벌 데이터 수정

---

apps/client/src/pages/time-table/hooks/use-scroll-position.ts

> - #242
타임테이블 페이지 로드시 편집하기 버튼 위로 올라가는 현상 수정
- 스크롤 확인 로직 변경

Fix(client): 타임테이블 페이지 로드시 편집하기 버튼 위로 올라가는 현상 수정

---

packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #251 
- 머지하면서 날아간 상단 배너 스타일 추가

Fix(design-system): 상단 배너 스타일 추가

---

apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
apps/client/src/pages/time-table/hooks/use-edit-mode.ts
apps/client/src/pages/time-table/hooks/use-patch-time-table-mutation.ts
apps/client/src/pages/time-table/page/time-table.tsx
apps/client/src/shared/apis/time-table/festival-button.ts
apps/client/src/shared/apis/time-table/festival-timetable.ts
apps/client/src/shared/types/timetable-response.ts

> - #250 
타임테이블 시간표 수정 API 연동
타임테이블 시간표 수정 API 연동

Feat(client): 타임테이블 시간표 수정 API 연동

---

apps/client/src/pages/my/page/profile/my-profile.tsx

> - #224 
관심 아티스트 목록 수정
- 아티스트 섹션에 표시되는 아티스트 수 제한

Fix(client): 관심 아티스트 목록 수정

---

apps/client/src/pages/search/components/performance-section.tsx
apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/mocks/searched-performance-data.ts
apps/client/src/pages/search/page/search.tsx
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/apis/search/search.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/search-reponse.ts

- #212 
- 검색된 아티스트 공연 정보 조회 api 연동했습니다.
https://github.com/user-attachments/assets/23275277-eaec-4d01-b64f-41b24fd4e286

Feat(client): 검색된 아티스트 공연 정보 조회 구현

---

apps/client/src/pages/home/page/home.tsx
apps/client/src/pages/my/components/artist/no-artist-section.tsx
apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx

* #255 
* navigate 설정
* 플로팅 버튼 터치 영역 개선

Feat(client): 아티스트 선택하기 버튼 기능구현

---

apps/client/src/pages/search/components/performance-info.css.ts
apps/client/src/pages/search/components/performance-info.tsx
apps/client/src/pages/search/components/performance-section.tsx
apps/client/src/pages/time-table/page/add-festival.tsx
apps/client/src/shared/mocks/performance-data.ts
apps/client/src/shared/types/performance-response.ts
apps/client/src/shared/types/search-reponse.ts
apps/client/src/shared/types/user-response.ts
packages/design-system/src/components/festival-card/festival-card.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #260 
- 좋아요 연결, 비로그인 토스트 연결
- 좋아요 연결 안돼있어서, 공연 목록 좋아요 연결하고 비로그인시 토스트창 뜨도록 연결했습니다~!
https://github.com/user-attachments/assets/4041498a-803f-4075-a01a-c4a7021f5341

Fix(client): (QA/4) 공연 목록 좋아요 연결, 비로그인 토스트 연결

---

packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #199 
상단 배너 클릭시 공연 상세보기로 이동합니다
- 상단 배너 클릭시 공연 상세보기로 이동
https://github.com/user-attachments/assets/58cb63cd-a1c1-4100-b665-8fe0fb47d032

Fix(design-system): (QA/4) 상단 배너 클릭 시 상세 페이지로 이동

---

apps/client/src/pages/search/components/performance-info.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #271 
- 비로그인 상세페이지 이동할 수 있도록 수정, 상단 배너 클릭시 outline 제거

Fix: 비로그인 상세페이지 이동할 수 있도록 수정, 상단 배너 클릭시 outline 제거

---

apps/client/src/pages/search/page/search.tsx

> - #266 
아티스트 없을 때 검색화면 예외처리 추가
- 아티스트 없을 때 검색화면 예외처리 추가

Feat(client): 아티스트 없을 때 검색화면 예외처리 추가

---

packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts

- #284 
- 패딩 값 조정으로 글자 중앙에 오게 수정했습니다.

Fix(client): ProgressBar 패딩 값 조정

---

apps/client/src/pages/my/page/profile/my-profile.tsx

> - #276 
더보기 버튼을 아티스트/페스티벌이 4개 이상일 때만 출현하도록 했습니다
- 아티스트/페스티벌이 4개 이상일 때 더보기 버튼 출현

Fix: (QA/4) 더보기 버튼 4개 이상일 때만 뜨도록 수정

---

apps/client/src/pages/search/page/search.tsx

검색 페이지 불필요한 변수 제거 및 코드 정리
검색 페이지 불필요한 변수 제거 및 코드 정리

Fix(client): 검색 페이지 불필요한 변수 제거 및 코드 정리

---

packages/design-system/src/components/ticketing-carousel/hooks/use-data-format.ts

* #290 
* use-data-format.ts 함수에서 데이터 포맷팅 로직을 수정합니다
* IOS 모바일 기기에서 포맷팅이 NaN 으로 패칭되던 버그를 해결합니다.
https://talkwithcode.tistory.com/3

Fix(client): 날짜 형식 변환 로직 수정 

---

packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts

- #287 
- description width 값 수정

Fix(client): description width 값 수정

---

apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
apps/client/src/pages/time-table/page/time-table.tsx

Fix: (QA/4) 플로팅 버튼 삭제하기 버그 수정 

---

.github/CODEOWNERS

> - #314
- CODEOWNERS 파일의 팀 소유자 변경

Fix: CODEOWNERS 변경

---

apps/client/src/pages/performance/components/info/info.css.ts

> - #297 
- 라벨 깨짐 현상을 해결했습니다
가격 라벨 외에도 전체적으로 컨텐츠가 길어지면 라벨이 세로정렬 되어서 라벨 전체에 flex shrink 속성을 추가했습니다
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/5649229f-24f0-4d31-b95b-299e7b85496d" width="400"></td>
<td><img src="https://github.com/user-attachments/assets/c15c039c-eb90-4343-bdb1-0b20b6a8e0d2" width="400"></td>
</tr>
</table>

Fix(client): 라벨 깨짐 현상 해결

---

apps/client/src/pages/my-history/page/record/my-record.tsx
apps/client/src/pages/my/components/profile/logout-section.tsx
apps/client/src/pages/my/page/setting/delete-account.tsx
packages/design-system/src/components/index.ts

> - #383 
로그아웃 모달을 추가했어요.
- 로그아웃 모달 추가
- useOverlay훅 export 방식 변경

Feat(client): 로그아웃 모달 추가

---

.github/workflows/discord-notify.yml
apps/client/src/pages/onboarding/components/artist-select.css.ts
apps/client/src/pages/onboarding/components/artist-select.tsx
apps/client/src/pages/onboarding/hooks/use-get-top-artist.ts
apps/client/src/pages/onboarding/page/onboarding.tsx
apps/client/src/shared/apis/onboard/top-artist-queries.ts
apps/client/src/shared/apis/onboard/top-artist.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/top-artist-response.ts

- #382 
- top100 아티스트 조회 api 를 연동합니다.
- api 타입 관련 이슈는 민하님이 한번 언급했기 때문에 추후에 고쳐보도록하겠슴다
개인적으로는 artist 이미지에 boxshadow가 있으면 어떠한가.. 하는 의견이 있어요 디자이너에게 한번 건의해보겠습니다

Feat(client): 탑 100 아티스트 조회 api 연동

---

apps/client/src/pages/home/components/suggest-music-section.tsx
apps/client/src/pages/home/hooks/use-home-queries.ts
apps/client/src/shared/apis/home/home-queries.ts
apps/client/src/shared/apis/home/home.ts
apps/client/src/shared/hooks/use-music-player.ts
apps/client/src/shared/types/home-response.ts
packages/design-system/src/components/music-list/music-list.tsx

> - #424 
Response Body가 변함에 따라 음악 관련 데이터 구조 및 타입을 변경했어요.
- 음악 관련 데이터 구조 및 타입 변경

Fix(client): 음악 관련 데이터 구조 및 타입 변경

---

apps/client/src/pages/search/components/search-home/popular-search-section.tsx
apps/client/src/pages/search/components/search-home/recent-search-section.tsx
apps/client/src/pages/search/hooks/use-recent-search.ts
apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/hooks/use-search-logic.ts
apps/client/src/pages/search/page/search-page.tsx
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/apis/search/search.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/search-reponse.ts

> - #430 
인기&최근 검색어 기능 구현
- 인기 검색어 API 연동
- 최근 검색어 localStorage관리 기능 구현
사실 제대로 작동하지 않는 부분이 많습니다.
새벽에 대대적인 리팩토링 후에 PR올릴게요.
리팩토링했더니 API구조가 바껴서 다시 구조를 싹 다 바꿔야하지만
어쩌겠어요. 정말 슬프네요.

Feat(client): 인기&최근 검색어 기능 구현

---

apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
apps/client/src/shared/types/my-history-response.ts

- #436 
변경된 response body에 맞춰서 타입 선언부 수정합니다.

Fix(client): 셋리스트 응답 타입에서 setlistCount를 totalCount로 변경

---

apps/client/index.html
apps/client/src/pages/home/page/home-page.tsx
apps/client/src/pages/login/hooks/use-social-login-mutation.ts
apps/client/src/pages/login/page/login.tsx
apps/client/src/shared/apis/auth/auth.ts
apps/client/src/shared/constants/api.ts
apps/client/src/shared/types/login-response.ts
apps/client/src/shared/utils/apple-login.ts

> - #438 
- 애플로그인 연동
- 배포환경 Redirect Url 설정
애플로그인은 http, localhost 환경을 모두 지원하지 않기때문에 
ngrok로 로컬 주소를 공개 서버로 바꿨습니다.
슬랙에 올려둘테니 해당 주소로 테스트 하시면 됩니다.

Feat(client): 애플로그인 연동

---

apps/client/src/shared/apis/auth/auth.ts

> - #445
배포환경 엔드포인트 변경 문제 해결
- 소셜로그인 엔드포인트 동적으로 변경 처리
배포환경에서 BASE_URL뒤에 '/'가 안붙는 이슈가 있어서 해결했어요.

Fix(client): 배포환경 엔드포인트 변경 문제 해결

---

packages/design-system/src/components/performance-carousel/performance-carousel.css.ts

> - #439 
- 공연 캐러셀 제목이 레이아웃 벗어나는 오류 수정

Fix(design-system): 공연 캐러셀 제목이 레이아웃 벗어나는 오류 수정

---

apps/client/src/shared/apis/auth/auth.ts
apps/client/src/shared/constants/api.ts

> - #447 
auth API에서 fetch를 axios로 변경했어요.
- fetch를 axios로 변경
- authInstance 생성

Fix(client): fetch를 axios로 변경

---

apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
apps/client/src/pages/time-table/hooks/use-festival-data.ts
apps/client/src/pages/time-table/hooks/use-festival-select.ts
apps/client/src/pages/time-table/page/time-table-page.tsx

Feat(client): 타임테이블 오류 수정

---

apps/client/src/pages/search/components/search-home/recent-festivals-section.tsx
apps/client/src/pages/search/hooks/use-search-data.ts
apps/client/src/pages/search/page/search-page.tsx
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/hooks/use-navigate-to-detail.ts

> - #454 
최근 검색결과 없을시 대체 텍스트 출력
- 최근 검색결과 없을시 대체 텍스트 출력
- type 대문자로 변환하여 네비게이션

Fix(client): 최근 검색결과 없을시 대체 텍스트 출력

---

apps/client/src/pages/performance/components/hero/hero.css.ts

> - #456 
상세페이지 타이틀 줄바꿈을 수정했어요.
- 띄어쓰기 단위로 줄바꿈
<table>
<tr>
<td>
<strong>전</strong><br />
</td>
<td>
<strong>후</strong><br />
</td>
</tr>
</table>

Refactor(client): 상세페이지 타이틀 줄바꿈 수정 

---

apps/client/src/pages/my-history/page/record/my-record.css.ts
apps/client/src/pages/my-history/page/record/my-record.tsx

Feat(client): 마이 히스토리 페이지 컴포넌트간 비율 수정

---

apps/client/src/pages/my/components/profile/user-info.tsx
apps/client/src/pages/my/page/edit/edit-profile.css.ts
apps/client/src/pages/my/page/edit/edit-profile.tsx
apps/client/src/shared/hooks/use-info-mutation.ts
packages/design-system/src/components/toast/toast-container.css.ts
packages/design-system/src/components/toast/toast.css.ts

> - #458
프로필 편집 페이지를 수정했어요
- 푸터 제거
- 버튼 하단 고정
- 아바타 선택 안 되게
https://github.com/user-attachments/assets/2df9fa8c-d445-4ecb-81a2-c9038a52b29b

Refactor(client): 프로필 편집 페이지 수정

---

apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
apps/client/src/pages/onboarding/components/onboarding-complete.tsx

Fix(client): 온보딩 완료 페이지에서 로고 크기 조정 및 정렬 수정

---

apps/client/src/pages/onboarding/components/artist-select.css.ts

Fix(client): 온보딩 아티스트 선택 페이지 모바일 대응

---

apps/client/src/pages/onboarding/components/artist-select.css.ts

Fix(client): 온보딩 페이지 스타일 수정

---

apps/client/src/shared/pages/auth/require-login-section.css.ts

Fix(client): require-login-section 스타일 수정하여 중앙 정렬 및 높이 조정

---

packages/design-system/src/components/search-suggestion-list/search-suggestion-list.stories.tsx
packages/design-system/src/components/skeleton/skeleton.css.ts
packages/design-system/src/components/skeleton/skeleton.stories.tsx
packages/design-system/src/components/skeleton/skeleton.tsx

- #477 
- 스켈레톤 컴포넌트를 구현했어요.
- mui 의 설계를 참고하였어요
- 기본적으로는 사각형의 스켈레톤이 생성되고, rounded, ractangle 이 있습니다
- 그리고 search-suggestion 스토리북의 type값을 변경된 response body에 맞춰서 수정했습니다. (기존에 에러 발생했음)
https://github.com/user-attachments/assets/b61120f8-4d94-4f39-81ce-207c30012a2f

Feat(design-system): 스켈레톤 컴포넌트 구현

---

apps/client/src/pages/home/components/performance-carousel-section.css.ts
apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
apps/client/src/pages/time-table/page/add-festival/add-festival.css.ts
apps/client/src/pages/time-table/page/add-festival/add-festival.tsx
packages/design-system/src/components/festival-card/festival-card.css.ts
packages/design-system/src/components/performance-carousel/performance-carousel.css.ts

> - #466 
- 홈/페스티벌 및 공연추가 페이지 스타일 수정
피그마와 동일하게 수정했습니다!

Fix(client): 홈/페스티벌 및 공연추가 페이지 스타일 수정

---

apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
apps/client/src/pages/my-history/page/add-songs/add-songs-page.css.ts
apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
packages/design-system/src/components/music-item/music-item.css.ts
packages/design-system/src/components/music-item/music-item.tsx
packages/design-system/src/components/music-list/music-list.tsx

> - #487 
곡 추가 페이지 음악재생 안되는 문제를 해결했어요
- 곡 추가 페이지 음악재생 안되는 문제 해결
@seueooo 혹시 여기서 MusicList를 안쓰고 MusicItem을 썼던 이유가 있을까요?

Fix(client): 곡 추가 페이지 음악재생 안되는 문제 해결

---

apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
apps/client/src/pages/my-history/hooks/use-prevent-scroll.ts
packages/design-system/src/components/music-item/music-item.css.ts

Fix(client): 드래그 훅 추가

---

apps/client/src/pages/timetable/page/empty/empty-festival-section.tsx
apps/client/src/pages/timetable/page/no-upcoming-festival/no-upcoming-festival.css.ts
apps/client/src/pages/timetable/page/no-upcoming-festival/no-upcoming-festival.tsx
apps/client/src/pages/timetable/page/timetable-layout.tsx
apps/client/src/shared/constants/links.ts
apps/client/src/shared/router/lazy.ts
apps/client/src/shared/router/path.ts
apps/client/src/shared/router/router.tsx

> - #557 
페스티벌 추가 없는 경우 나타나는 페이지를 제작합니다.
- 페스티벌 추가 없는 경우 페이지 제작

Feat(client): 페스티벌 추가 없는 경우 페이지 제작

---

apps/client/src/App.tsx
apps/client/src/shared/router/router.tsx
apps/client/src/shared/router/routes/auth-routes.tsx
apps/client/src/shared/router/routes/fallback-routes.tsx
apps/client/src/shared/router/routes/global-routes.tsx
apps/client/src/shared/router/routes/my-page-routes.tsx
apps/client/src/shared/router/routes/my-record-routes.tsx
apps/client/src/shared/router/routes/timetable-routes.tsx

> - #549 
createBrowserRouter로 라우터를 개선합니다.
- `createBrowserRouter` 및 `RouterProvider` 적용
- `routes/` 디렉토리 내 도메인 기준 라우트 파일 분리
라우터 파일 구조 위주로 확인 부탁드려요!

Refactor(client): Router 개선

---

.vscode/settings.json
apps/client/src/pages/my-history/components/overview/order-by-button.css.ts
apps/client/src/pages/my-history/components/record/record-info.css.ts
apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
apps/client/src/pages/my/hooks/use-logout-mutation.ts
apps/client/src/pages/my/page/setting/setting.css.ts
apps/client/src/pages/my/page/setting/setting.tsx
apps/client/src/pages/search/components/search-result/artist/artist-not-found.css.ts
apps/client/src/pages/search/components/search-result/artist/artist-not-found.tsx
apps/client/src/pages/search/hooks/use-search-logic.ts
apps/client/src/pages/search/page/search-page.tsx
apps/client/src/pages/search/page/search-result-page.css.ts
apps/client/src/pages/search/page/search-result-page.tsx
apps/client/src/pages/timetable/components/onboard/intro-step.tsx
apps/client/src/pages/timetable/page/empty/empty-festival-section.css.ts
apps/client/src/shared/apis/search/search-queries.ts
apps/client/src/shared/constants/query-key.ts
packages/design-system/src/components/toast/toast.css.ts
packages/design-system/src/styles/reset.css.ts

Fix(client): (QA/6) QA사항 반영

---

apps/client/src/pages/home/components/suggest-performance-section.css.ts
apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
apps/client/src/shared/utils/format-date.ts

> - #591 
QA를 반영했어요.
- 셋리스트 문장에 온점 추가
- 동일 날짜인 경우 기간대신에 단일 날짜 뜨도록 변경
- 홈 캐러셀 우측에 여백 추가

Fix(client): QA 반영

---

apps/client/src/pages/timetable/components/festival-selector/festival-selector.tsx
packages/design-system/src/components/performance-carousel/performance-carousel.tsx

> - #592 
- 캐러셀 오버레이 추가
임시방편으로 overlay svg tsx 긁어와서 추가했어요..ㅎ 나중에 background로 바꾸겠습니다.

Refactor(design-system): 캐러셀 오버레이 추가

---

apps/client/src/pages/onboarding/components/artist-select.css.ts
apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
pnpm-lock.yaml

> - #601 
온보딩 페이지에서 스크롤을 내려야 버튼이 보이는 이슈를 해결합니다.
- 온보딩 페이지 스크롤 이슈 해결

Fix(client): 온보딩 스크롤 이슈 해결

---

apps/client/index.html

> - #635 
Hotjar 추적 스크립트를 추가했어요.
- Hotjar 추적 스크립트 추가
hjid는 브라우저에서 노출되는 공개 정보이기에 별도의 env파일로 분리하지 않았어요.

Feat(client): Hotjar 추적 스크립트 추가

---

apps/client/src/pages/timetable/page/timetable-content/timetable-content.tsx
apps/client/src/shared/apis/timetable/festival-timetable-mutation.ts
apps/client/src/shared/constants/api.ts

Feat: screenshot api 연결

---

apps/client/src/shared/constants/api.ts
apps/client/src/shared/router/onboarding-guard.tsx
apps/client/src/shared/types/onboard-response.ts

- #642 
- https://weareconfeti.slack.com/archives/C08K7RMK1FS/p1753343674823269 
위 슬랙 스레드에서 언급 된 이슈로 api url 및 응답 값이 변경되었어요. 이 부분을 반영하였습니다.

Fix(client): 온보딩 status 변경 된 스펙 반영

---

apps/client/src/pages/performance/components/artist/festival-artist-section.tsx

- #639 
https://www.notion.so/249210e281b0807db4f5d214b1e3aa20?source=copy_link
https://www.notion.so/4-249210e281b08036a58dc4e8ee65714e?source=copy_link
노션에 언급된 qa 진행했습니다

Fix(client): avatar 컴포넌트 클릭 false 처리 및 morebutton 조건 수정
